routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','userController@index');

Route::resource('user','userController');

Route::get('/show','ViewController@show');

Route::get('/edit','ViewController@edit');

Route::get('/create','ViewController@create');

Auth::routes();

Route::get('messages', 'ChatsController@fetchMessages');
Route::post('messages', 'ChatsController@sendMessage');
Route::get('/chat', 'ChatsController@index');
Route::get('/edit_report',function()
           {
              return view('edit_report'); 
           });
Route::resource('post','postController');
Route::get('/user_reports','ReportController@index');

Route::resource('admin','adminController');
Route::get('/adminview',function(){
    
    return view('adminview');
});
Route::get('admin-template',function(){
    
    return view('admin-template');
    
});

Route::resource('projects','projectsController');

Route::get('/create_project','createProjectController@index');

Route::get('/edit_project',function(){
    
    return view('edit_project');
});

Route::get('/admin_dashboard','ViewController@dashboard');
Route::get('/user_dashboard','ViewController@dashboard');
Route::resource('/participate','ParticipantController');
Route::get('profile','ViewController@profile');
Route::post('/test','groupController@index');

resources/views/admin_dashboard.blade.php
@extends('admin-template')


@section('content-left')
<br><br><br>
<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">All the users</h3>
			</div>
			<table class="table">
				<thead>
					<tr>
						<th>#</th>
						<th>Name</th>
						<th></th>
						<th></th>
						
                    <th>Reports</th>
					</tr>
				</thead>
				<tbody>
					@foreach ($users as $user)
						<tr>
							<td>{!! $user->id !!}</td>
							<td class="text-primary"><strong>{!! $user->name !!}</strong></td>
							
							<td>{!! link_to_route('user.edit', 'Edit', [$user->id], ['class' => 'btn btn-warning btn-block']) !!}</td>
							<td>
								{!! Form::open(['method' => 'DELETE', 'route' => ['user.destroy', $user->id]]) !!}
									{!! Form::submit('Delete', ['class' => 'btn btn-danger btn-block', 'onclick' => 'return confirm(\'Do you really want to delete this user ?\')']) !!}
								{!! Form::close() !!}
							</td>
                            <td> 
                            {!!link_to_route('admin.show', 'dashboard',[$user->id],['class'=>'btn btn-primary'])!!}
                            
                            </td>
						</tr>
					@endforeach
	  			</tbody>
			</table>
		</div>
		{!! link_to_route('user.create', 'Add a user', [], ['class' => 'btn btn-info pull-right']) !!}
		{!! $links !!}
<!---/Reports-->
<br><br><br><br>
    
    	
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">Reports of {{Auth::user()->name}}</h3>
			</div>
            
			<table class="table">
				<thead>
					<tr>
						<th>#</th>
						<th>Title</th>
						<th></th>
						<th></th>
						<th></th>
                                                
					</tr>
				</thead>
				<tbody>
					@foreach ($self_reports as $report)
						<tr>
							<td>{!! $report->created_at !!}</td>
							<td class="text-primary"><strong>{!! $report->title !!}</strong></td>
							<td>{!! link_to_route('post.show', 'See report', [$report->id], ['class' => 'btn btn-success btn-block']) !!}</td>
							<td>{!! link_to_route('post.edit', 'Edit', [$report->id], ['class' => 'btn btn-warning btn-block']) !!}</td>
							<td>
								{!! Form::open(['method' => 'DELETE', 'route' => ['post.destroy', $report->id]]) !!}
									{!! Form::submit('Delete', ['class' => 'btn btn-danger btn-block', 'onclick' => 'return confirm(\'Do you really want to delete this report ?\')']) !!}
								{!! Form::close() !!}
							</td>
                            
						</tr>
					@endforeach
	  			</tbody>
			</table>
		</div>
		{!! link_to_route('post.create', 'Add a  report', [], ['class' => 'btn btn-info pull-right']) !!}
		{!! $self_reports_pages !!}


<!---Participating Project-->
<br><br><br>
    
    	
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">  Projects Which {{Auth::user()->name}} Contributes</h3>
			</div>
            
			<table class="table">
				<thead>
					<tr>
						<th>#</th>
						<th>Project Code</th>
						<th></th>
						<th></th>
						<th></th>
                                                
					</tr>
				</thead>
				<tbody>
					@foreach ($participates_projects as $project)
						<tr>
							<td>{!! $project->created_at !!}</td>
							<td class="text-primary"><strong>{!! $project->code !!}</strong></td>
							<td>{!! link_to_route('projects.show', 'See Project', [$project->id], ['class' => 'btn btn-success btn-block']) !!}</td>
							<td>{!! link_to_route('projects.edit', 'Edit', [$project->id], ['class' => 'btn btn-warning btn-block']) !!}</td>
							<td>
								{!! Form::open(['method' => 'DELETE', 'route' => ['projects.destroy', $project->id]]) !!}
									{!! Form::submit('Close', ['class' => 'btn btn-danger btn-block', 'onclick' => 'return confirm(\'Do you really want to close this project ?\')']) !!}
								{!! Form::close() !!}
							</td>
                            
						</tr>
					@endforeach
	  			</tbody>
			</table>
		</div>
		
		{!! $participate_links !!}

<!--- Participating project end -->



@endsection


@section('content-right')
<br><br><br>
    
    	
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">Active Projects of {{Auth::user()->name}}</h3>
			</div>
            
			<table class="table">
				<thead>
					<tr>
						<th>#</th>
						<th>Project Code</th>
						<th></th>
						<th></th>
						<th></th>
                                                
					</tr>
				</thead>
				<tbody>
					@foreach ($self_projects as $project)
						<tr>
							<td>{!! $project->created_at !!}</td>
							<td class="text-primary"><strong>{!! $project->code !!}</strong></td>
							<td>{!! link_to_route('projects.show', 'See Project', [$project->id], ['class' => 'btn btn-success btn-block']) !!}</td>
							<td>{!! link_to_route('projects.edit', 'Edit', [$project->id], ['class' => 'btn btn-warning btn-block']) !!}</td>
							<td>
								{!! Form::open(['method' => 'DELETE', 'route' => ['projects.destroy', $project->id]]) !!}
									{!! Form::submit('Close', ['class' => 'btn btn-danger btn-block', 'onclick' => 'return confirm(\'Do you really want to close this project ?\')']) !!}
								{!! Form::close() !!}
							</td>
                            
						</tr>
					@endforeach
	  			</tbody>
			</table>
		</div>
		{!! link_to_route('projects.create', 'Add a  project', [], ['class' => 'btn btn-info pull-right']) !!}
		{!! $self_projects_pages!!}

<!--Closed projects-->

<br><br><br><br>
    
    	
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">Closed Projects of {{Auth::user()->name}}</h3>
			</div>
            
			<table class="table">
				<thead>
					<tr>
						<th>#</th>
						<th>Project Code</th>
						<th></th>
						<th></th>
						<th></th>
                                                
					</tr>
				</thead>
				<tbody>
					@foreach ($Closed_projects as $project)
						<tr>
							<td>{!! $project->created_at !!}</td>
							<td class="text-primary"><strong>{!! $project->code !!}</strong></td>
							<td>{!! link_to_route('projects.show', 'See Project', [$project->id], ['class' => 'btn btn-success btn-block']) !!}</td>
							<td>{!! link_to_route('projects.edit', 'Edit', [$project->id], ['class' => 'btn btn-warning btn-block']) !!}</td>
							<td>
								<a href="#" class="btn btn-danger" role="button" disabled> Closed</a>
							</td>
                            
						</tr>
					@endforeach
	  			</tbody>
			</table>
		</div>
		
		{!! $projects_pages !!}


<!-- Closed projects end -->

<!-- Managing projects -->

<br><br><br>
    
    	
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">Managing Projects of {{Auth::user()->name}}</h3>
			</div>
            
			<table class="table">
				<thead>
					<tr>
						<th>#</th>
						<th>Project Code</th>
						<th></th>
						<th></th>
						<th></th>
                                                
					</tr>
				</thead>
				<tbody>
					@foreach ($manage_project as $project_man)
                     @if($project_man->status==1)
						<tr>
							<td>{!! $project->created_at !!}</td>
							<td class="text-primary"><strong>{!! $project_man->code !!}</strong></td>
							<td>{!! link_to_route('projects.show', 'See Project', [$project_man->id], ['class' => 'btn btn-success btn-block']) !!}</td>
							<td>{!! link_to_route('projects.edit', 'Edit', [$project_man->id], ['class' => 'btn btn-warning btn-block']) !!}</td>
							<td>
								{!! Form::open(['method' => 'DELETE', 'route' => ['projects.destroy', $project_man->id]]) !!}
									{!! Form::submit('Close', ['class' => 'btn btn-danger btn-block', 'onclick' => 'return confirm(\'Do you really want to close this project ?\')']) !!}
								{!! Form::close() !!}
							</td>
                            
						</tr>
                    @endif
					@endforeach
	  			</tbody>
			</table>
		</div>
		
		{!! $manage_links !!}

<!--Maning Projects End -->





@endsection

resources/views/chat.blade.php
<!-- resources/views/chat.blade.php -->

@extends('single-post-template')

@section('content')
<br><br><br><br><br><br>
<div class="col-sm-offset-2 col-sm-8">
@if(session()->has('ok'))
			<div class="alert alert-success alert-dismissible">{!! session('ok') !!}</div>
@elseif($errors->any())
     <div class="alert alert-danger">{!!$errors->first()!!}</div>
@endif
</div>


<div class="col-sm-offset-2 col-sm-8">
<div class="alert alert-success text-center"> You can upload files as well  </div>
{{Form::open(['route' => 'post.store'])}}
<div class="box-body">
<div class="form-group">

{{Form::text('title',null,array('class' => 'form-control', 'placeholder'=>'Title'))}}
</div>
<div class="form-group">
{{Form::label('body', 'Content')}}
{{Form::textarea('body',null,array('class' => 'form-control', 'placeholder'=>'Content', 'id' => 'summernote'))}}
</div>
<div class="form-group">
     {{Form::submit('Publish Post',array('class' => 'btn btn-primary btn-sm pull-right'))}} </div>
{{Form::close()}}
</div>
    <a href="javascript:history.back()" class="btn btn-primary">
			<span class="glyphicon glyphicon-circle-arrow-left"></span> Back
		</a>
</div>
@endsection

resources/views/create.blade.php
@extends('single-content')

@section('content')
	<div class="col-sm-offset-4 col-sm-4">
		<br>
		<div class="panel panel-primary">	
			<div class="panel-heading">Create new user
            @if ($errors->any())
                <h4 class="alert alert-danger">{{$errors->first()}}</h4>
                @endif
            </div>
			<div class="panel-body"> 
				<div class="col-sm-12">
					{!! Form::open(['route' => 'user.store', 'class' => 'form-horizontal panel']) !!}	
					<div class="form-group {!! $errors->has('name') ? 'has-error' : '' !!}">
						{!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Name']) !!}
						{!! $errors->first('name', '<small class="help-block">:message</small>') !!}
					</div>
					<div class="form-group {!! $errors->has('email') ? 'has-error' : '' !!}">
						{!! Form::email('email', null, ['class' => 'form-control', 'placeholder' => 'Email']) !!}
						{!! $errors->first('name', '<small class="help-block">:message</small>') !!}
					</div>
					<div class="form-group {!! $errors->has('password') ? 'has-error' : '' !!}">
						{!! Form::password('password', ['class' => 'form-control', 'placeholder' => 'Password']) !!}
						{!! $errors->first('password', '<small class="help-block">:message</small>') !!}
					</div>
					<div class="form-group">
						{!! Form::password('password_confirmation', ['class' => 'form-control', 'placeholder' => 'Confirm password']) !!}
					</div>
					<div class="form-group">
						<div class="checkbox">
							<label>
								{!! Form::checkbox('admin', 1, null) !!} Administrator
							</label>
						</div>
					</div>
					{!! Form::submit('Send', ['class' => 'btn btn-primary pull-right']) !!}
					{!! Form::close() !!}
				</div>
			</div>
		</div>
		<a href="javascript:history.back()" class="btn btn-primary">
			<span class="glyphicon glyphicon-circle-arrow-left"></span> Back
		</a>
	</div>
@endsection

resources/views/create_project.blade.php
@extends('create-project-template')


@section('content')

<div class="panel panel-primary">	
			<div class="panel-heading">Create new project
            @if ($errors->any())
                <h4 class="alert alert-danger">{{$errors->first()}}</h4>
                @endif
            </div>
    
			<div class="panel-body"> 
				<div class="col-sm-12">
					{!! Form::open(['route' => 'projects.store', 'class' => 'form-horizontal panel']) !!}	
					<div class="form-group {!! $errors->has('code') ? 'has-error' : '' !!}">
						{!! Form::text('code', null, ['class' => 'form-control', 'placeholder' => 'Project code']) !!}
						{!! $errors->first('code', '<small class="help-block">:message</small>') !!}
					</div>
					<div class="form-group {!! $errors->has('type') ? 'has-error' : '' !!}">
						{!! Form::number('type', null, ['class' => 'form-control', 'placeholder' => 'Type']) !!}
						{!! $errors->first('type', '<small class="help-block">:message</small>') !!}
					</div>
					<div class="form-group {!! $errors->has('project_name') ? 'has-error' : '' !!}">
						{!! Form::text('project_name',null, ['class' => 'form-control', 'placeholder' => 'Project name']) !!}
						{!! $errors->first('project_name', '<small class="help-block">:message</small>') !!}
					</div>
					<div class="form-group">
                        {!!Form::label('managerName','Project Manager')!!}
						{!! Form::select('manager', $users,null, ['class'=> 'form-control','id'=>'managerName'])  !!}
					</div>
					<div class="form-group">
						    {{Form::label('content', 'Content')}}
							{{Form::textarea('content',null,array('class' => 'form-control', 'placeholder'=>'Content', 'id' => 'summernote'))}}
						</div>
                      <hr>
                   
					</div>
					{!! Form::submit('Send', ['class' => 'btn btn-primary pull-right']) !!}
					{!! Form::close() !!}
				</div>
			</div>
		
		<a href="javascript:history.back()" class="btn btn-primary">
			<span class="glyphicon glyphicon-circle-arrow-left"></span> Back
		</a>


@endsection

resources/views/edit.blade.php
@extends('single-content')

@section('content')
    <div class="col-sm-offset-4 col-sm-4">
    	<br>
		<div class="panel panel-primary">	
			<div class="panel-heading">Edit user</div>
			<div class="panel-body"> 
				<div class="col-sm-12">
					{!! Form::model($user, ['route' => ['user.update', $user->id], 'method' => 'put', 'class' => 'form-horizontal panel']) !!}
					<div class="form-group {!! $errors->has('name') ? 'has-error' : '' !!}">
					  	{!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Name']) !!}
					  	{!! $errors->first('name', '<small class="help-block">:message</small>') !!}
					</div>
					<div class="form-group {!! $errors->has('email') ? 'has-error' : '' !!}">
					  	{!! Form::email('email', null, ['class' => 'form-control', 'placeholder' => 'Email']) !!}
					  	{!! $errors->first('email', '<small class="help-block">:message</small>') !!}
					</div>
					<div class="form-group">
						<div class="checkbox">
							<label>
								{!! Form::checkbox('admin', 1, null) !!}Administrateur
							</label>
						</div>
					</div>
						{!! Form::submit('Send', ['class' => 'btn btn-primary pull-right']) !!}
					{!! Form::close() !!}
				</div>
			</div>
		</div>
		<a href="javascript:history.back()" class="btn btn-primary">
			<span class="glyphicon glyphicon-circle-arrow-left"></span> Back
		</a>
	</div>
@endsection

resources/views/edit_project.blade.php
@extends('create-project-template')


@section('content')

<div class="panel panel-primary">	
			<div class="panel-heading">Edit project {{$project->project_name}}
            @if ($errors->any())
                <h4 class="alert alert-danger">{{$errors->first()}}</h4>
                @endif
            </div>
    
			<div class="panel-body"> 
				<div class="col-sm-12">
					{!! Form::model($project, ['route' => ['projects.update', $project->id], 'method' => 'put', 'class' => 'form-horizontal panel']) !!}	
					<div class="form-group {!! $errors->has('code') ? 'has-error' : '' !!}">
						{!! Form::text('code', null, ['class' => 'form-control', 'placeholder' => 'Project code']) !!}
						{!! $errors->first('code', '<small class="help-block">:message</small>') !!}
					</div>
					<div class="form-group {!! $errors->has('type') ? 'has-error' : '' !!}">
						{!! Form::number('type', null, ['class' => 'form-control', 'placeholder' => 'Type']) !!}
						{!! $errors->first('type', '<small class="help-block">:message</small>') !!}
					</div>
					<div class="form-group {!! $errors->has('name') ? 'has-error' : '' !!}">
						{!! Form::text('name',$project->project_name, ['class' => 'form-control', 'placeholder' => 'Project name']) !!}
						{!! $errors->first('name', '<small class="help-block">:message</small>') !!}
					</div>
					<div class="form-group">
                        {!!Form::label('managerName','Project Manager')!!}
						{!! Form::select('manager', $users,null, ['class'=> 'form-control','id'=>'managerName'])  !!}
					</div>
					<div class="form-group">
						    {{Form::label('content', 'Content')}}
							{{Form::textarea('content',null,array('class' => 'form-control', 'placeholder'=>'Content', 'id' => 'summernote'))}}
						</div>
                      <hr>
                   
					</div>
					{!! Form::submit('Send', ['class' => 'btn btn-primary pull-right']) !!}
					{!! Form::close() !!}
				</div>
			</div>
		
		<a href="javascript:history.back()" class="btn btn-primary">
			<span class="glyphicon glyphicon-circle-arrow-left"></span> Back
		</a>


@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/profile.blade.php
@extends('single-content')

@section('content')
    <div class="col-sm-offset-2 col-sm-8">
    	<br>
		<div class="panel panel-primary">	
			<div class="panel-heading">About user</div>
			<div class="panel-body"> 
				<p>Name : {{ $user->name }}</p>
				<p>Email : {{ $user->email }}</p>
				@if($user->admin == 1)
					Administrator
				@endif
			</div>
            
            
            
		</div>
        {!! link_to_route('user.edit', 'Edit', [$user->id], ['class' => 'btn btn-warning btn-block pull-right']) !!}
        <br><br><br>
		<a href="javascript:history.back()" class="btn btn-primary">
			<span class="glyphicon glyphicon-circle-arrow-left"></span> Back
		</a>
	</div>
@endsection

resources/views/show.blade.php
@extends('single-content')

@section('content')
    <div class="col-sm-offset-2 col-sm-8">
    	<br>
		<div class="panel panel-primary">	
			<div class="panel-heading">About user</div>
			<div class="panel-body"> 
				<p>Name : {{ $user->name }}</p>
				<p>Email : {{ $user->email }}</p>
				@if($user->admin == 1)
					Administrator
				@endif
			</div>
		</div>				
		<a href="javascript:history.back()" class="btn btn-primary">
			<span class="glyphicon glyphicon-circle-arrow-left"></span> Back
		</a>
	</div>
@endsection

resources/views/user.blade.php
@extends('admin-template')

@section('content-left')
    <br>
    
    	@if(session()->has('ok'))
			<div class="alert alert-success alert-dismissible">{!! session('ok') !!}</div>
		@endif
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">All the users</h3>
			</div>
			<table class="table">
				<thead>
					<tr>
						<th>#</th>
						<th>Name</th>
						<th></th>
						<th></th>
						<th></th>
                    <th>Reports</th>
					</tr>
				</thead>
				<tbody>
					@foreach ($users as $user)
						<tr>
							<td>{!! $user->id !!}</td>
							<td class="text-primary"><strong>{!! $user->name !!}</strong></td>
							<td>{!! link_to_route('user.show', 'See more', [$user->id], ['class' => 'btn btn-success btn-block']) !!}</td>
							<td>{!! link_to_route('user.edit', 'Edit', [$user->id], ['class' => 'btn btn-warning btn-block']) !!}</td>
							<td>
								{!! Form::open(['method' => 'DELETE', 'route' => ['user.destroy', $user->id]]) !!}
									{!! Form::submit('Delete', ['class' => 'btn btn-danger btn-block', 'onclick' => 'return confirm(\'Do you really want to delete this user ?\')']) !!}
								{!! Form::close() !!}
							</td>
                            <td> 
                            {!!link_to_route('admin.show', 'See Reports',[$user->id],['class'=>'btn btn-primary'])!!}
                            
                            </td>
						</tr>
					@endforeach
	  			</tbody>
			</table>
		</div>
		{!! link_to_route('user.create', 'Add a user', [], ['class' => 'btn btn-info pull-right']) !!}
		{!! $links !!}
	
@endsection

resources/views/user_dashboard.blade.php
@extends('admin-template')


@section('content-left')

<!---/Reports-->
<br><br><br>
    
    	
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">Reports of {{Auth::user()->name}}</h3>
			</div>
            
			<table class="table">
				<thead>
					<tr>
						<th>#</th>
						<th>Title</th>
						<th></th>
						<th></th>
						<th></th>
                                                
					</tr>
				</thead>
				<tbody>
					@foreach ($self_reports as $report)
						<tr>
							<td>{!! $report->created_at !!}</td>
							<td class="text-primary"><strong>{!! $report->title !!}</strong></td>
							<td>{!! link_to_route('post.show', 'See report', [$report->id], ['class' => 'btn btn-success btn-block']) !!}</td>
							<td>{!! link_to_route('post.edit', 'Edit', [$report->id], ['class' => 'btn btn-warning btn-block']) !!}</td>
							<td>
								{!! Form::open(['method' => 'DELETE', 'route' => ['post.destroy', $report->id]]) !!}
									{!! Form::submit('Delete', ['class' => 'btn btn-danger btn-block', 'onclick' => 'return confirm(\'Do you really want to delete this report ?\')']) !!}
								{!! Form::close() !!}
							</td>
                            
						</tr>
					@endforeach
	  			</tbody>
			</table>
		</div>
		{!! link_to_route('post.create', 'Add a  report', [], ['class' => 'btn btn-info pull-right']) !!}
		{!! $self_reports_pages !!}
<!-- Participating Project -->
<br><br><br>
    
    	
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">Projects Which {{Auth::user()->name}} Contributes</h3>
			</div>
            
			<table class="table">
				<thead>
					<tr>
						<th>#</th>
						<th>Project Code</th>
						<th></th>
						<th></th>
						
                                                
					</tr>
				</thead>
				<tbody>
					@foreach ($participates_projects as $project)
						<tr>
							<td>{!! $project->created_at !!}</td>
							<td class="text-primary"><strong>{!! $project->code !!}</strong></td>
							<td>{!! link_to_route('participate.show', 'See Project', [$project->id], ['class' => 'btn btn-success btn-block']) !!}</td>
							<td>{!! link_to_route('projects.edit', 'Edit', [$project->id], ['class' => 'btn btn-warning btn-block']) !!}</td>
							
                            
						</tr>
					@endforeach
	  			</tbody>
			</table>
		</div>
		
		{!! $participate_links !!}

<!-- Participating projects end -->


@endsection


@section('content-right')
<br><br><br>
    
    	
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">Active Projects of {{Auth::user()->name}}</h3>
			</div>
            
			<table class="table">
				<thead>
					<tr>
						<th>#</th>
						<th>Project Code</th>
						<th></th>
						<th></th>
						<th></th>
                                                
					</tr>
				</thead>
				<tbody>
					@foreach ($self_projects as $project)
						<tr>
							<td>{!! $project->created_at !!}</td>
							<td class="text-primary"><strong>{!! $project->code !!}</strong></td>
							<td>{!! link_to_route('projects.show', 'See Project', [$project->id], ['class' => 'btn btn-success btn-block']) !!}</td>
							<td>{!! link_to_route('projects.edit', 'Edit', [$project->id], ['class' => 'btn btn-warning btn-block']) !!}</td>
							<td>
								
							</td>
                            
						</tr>
					@endforeach
	  			</tbody>
			</table>
		</div>
		{!! link_to_route('projects.create', 'Add a  project', [], ['class' => 'btn btn-info pull-right']) !!}
		{!! $self_projects_pages!!}

<!--Closed projects-->

<!-- Closed projects end -->

<!-- Managing projects -->

<br><br><br>
    
    	
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title"> Projects Which {{Auth::user()->name}} Manages</h3>
			</div>
            
			<table class="table">
				<thead>
					<tr>
						<th>#</th>
						<th>Project Code</th>
						<th></th>
						<th></th>
						<th></th>
                                                
					</tr>
				</thead>
				<tbody>
					@foreach ($manage_project as $project)
						<tr>
							<td>{!! $project->created_at !!}</td>
							<td class="text-primary"><strong>{!! $project->code !!}</strong></td>
							<td>{!! link_to_route('projects.show', 'See Project', [$project->id], ['class' => 'btn btn-success btn-block']) !!}</td>
							<td>{!! link_to_route('projects.edit', 'Edit', [$project->id], ['class' => 'btn btn-warning btn-block']) !!}</td>
							<td>
								
							</td>
                            
						</tr>
					@endforeach
	  			</tbody>
			</table>
		</div>
		
		{!! $manage_links !!}

<!--Maning Projects End -->



@endsection

resources/views/user_reports.blade.php
@extends('single-post-template')

@section('content')


<br><br><br><br>
    <div class="col-sm-offset-2 col-sm-8">
    	@if(session()->has('ok'))
			<div class="alert alert-success alert-dismissible">{!! session('ok') !!}</div>
		@endif
        
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">Reports of {{Auth::user()->name}}</h3>
			</div>
            
			<table class="table">
				<thead>
					<tr>
						<th>#</th>
						<th>Title</th>
						<th></th>
						<th></th>
						<th></th>
                                                
					</tr>
				</thead>
				<tbody>
					@foreach ($reports as $report)
						<tr>
							<td>{!! $report->created_at !!}</td>
							<td class="text-primary"><strong>{!! $report->title !!}</strong></td>
							<td>{!! link_to_route('post.show', 'See report', [$report->id], ['class' => 'btn btn-success btn-block']) !!}</td>
							<td>{!! link_to_route('post.edit', 'Edit', [$report->id], ['class' => 'btn btn-warning btn-block']) !!}</td>
							<td>
								{!! Form::open(['method' => 'DELETE', 'route' => ['post.destroy', $report->id]]) !!}
									{!! Form::submit('Delete', ['class' => 'btn btn-danger btn-block', 'onclick' => 'return confirm(\'Do you really want to delete this report ?\')']) !!}
								{!! Form::close() !!}
							</td>
                            
						</tr>
					@endforeach
	  			</tbody>
			</table>
		</div>
		{!! link_to_route('post.create', 'Add a  report', [], ['class' => 'btn btn-info pull-right']) !!}
		{!! $links !!}
	</div>



@endsection